---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```
#Read xlxs

```{r}

excel <- read_excel("data/datos.xlsx", col_types= c("numeric", "text", "date", "text", "numeric", "text", "numeric",
"numeric", "numeric", "numeric", "numeric", "numeric"))




new_dat <- excel %>%
  mutate(no_asignados = ifelse(SALUD + OTROS + VIAJES + DEUDAS + BANCO == 1, 0, 1)) %>%
  mutate(error_asig   = ifelse(SALUD + OTROS + VIAJES + DEUDAS + BANCO > 1,TRUE, FALSE)) %>%
  mutate(incumplio    = ifelse(SALUD + OTROS + VIAJES + DEUDAS + BANCO == 1 & PAGO == 0,1, 0))

```

#cuantos 
no_asignados : registros que no tienen una tipo de deudad asignado 
error_asig   : verificar si el registro no tiene mas de 1 tipo de deuda
incumplio    : validar si tiene una deuda pero no pago 
```{r}
print(summary(new_dat$incumplio == 1))
```

```{r}
ggplot(new_dat, aes(TIPO,PAGO)) +
  geom_boxplot() +
   labs(title = "Tipos de pago")
```

# plOt para verificar los meses con pagos mas altos dentro de la data

```{r}

ggplot(new_dat %>% na.omit(), aes(factor(month(FECHA, label = TRUE)),PAGO)) +
  geom_boxplot() +
   labs(title = "PAGOS POR MES")
```

